# Generated by Django 4.0 on 2021-12-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
